[[constraint]]
  name = "github.com/covexo/yamlq"
  revision = "ee51b09a773c7e7e4e32168cbec4d47a014161b4"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "v0.3.6"

[[constraint]]
  name = "github.com/juju/errors"
  revision = "22422dad46e14561a0854ad42497a75af9b61909"

[[constraint]]
  name = "github.com/docker/docker"
  source = "https://github.com/moby/moby"
  revision = "ae7016427f8cba4e4d8fcb979d6ba313ee2c0702"

[[constraint]]
  name = "github.com/docker/cli"
  version = "v18.06.1-ce"

[[constraint]]
  name = "github.com/rhysd/go-github-selfupdate"
  revision = "41c1bbb0804a2994dae69502a8c76e7c456ad45e"

[[constraint]]
  name = "github.com/sabhiram/go-gitignore"
  version = "1.0.2"

[[constraint]]
  name = "github.com/daviddengcn/go-colortext"
  revision = "186a3d44e9200d7eb331356ca4864f52708e1399"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/otiai10/copy"
  revision = "7e9a647135a142c2669943d4a4d29be015ce9392"

[[constraint]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.9.1"

[[constraint]]
  name = "github.com/foomo/htpasswd"
  revision = "cb63c4ac0e5029b961b3ac7dcc281ed2a9232e4e"

[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  version = "1.1.1"

[[constraint]]
  name = "github.com/badgerodon/penv"
  revision = "7a4c6d64fa119b52afe2eb3f0801886bd8785318"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "ba92f7aebfda56086efd08a6b231c6b60a297d2d"

[[override]]
  name = "k8s.io/api"
  revision = "12444147eb1150aa5c80d2aae532cbc5b7be73d0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "e386b2658ed20923da8cc9250e552f082899a1ee"

[[override]]
  name = "k8s.io/apiserver"
  revision = "2a84596e9aad63b1c1d47491d506a64465b5e2fc"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "f584b16eb23bd2a3fd292a027d698d95db427c5d"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.1"

[[override]]
  name = "github.com/docker/distribution"
  revision = "a97d7c0c155be14d1380c075d3197a5d89c2abc2"

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.6"
  
[prune]
  go-tests = true
  unused-packages = true
