version: v1alpha1
cluster:
  cloudProvider: devspace-cloud
devSpace:
  deployments:
  - helm:
      chartPath: ./chart
    name: devspace-default
  ports:
  - labelSelector:
      release: devspace-default
    portMappings:
    - localPort: 3000
      remotePort: 3000
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-default
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - node_modules/
images:
  default:
    name: yourdockername/devspace
