name: Test NPM Installer

on:
  pull_request:
    branches:
      - master
    paths:
      - "dist/npm/**"
      - ".github/workflows/npm.yaml"

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install -g
          npm run prepare
          devspace --version
          npm uninstall -g devspace

          npx -p . devspace --version

          export PATH=$PATH:$(yarn global bin)

          yarn global add $PWD
          devspace --version
          yarn global remove devspace
        working-directory: ./dist/npm
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install -g
          npm run prepare
          devspace --version
          npm uninstall -g devspace

          npx -p . devspace --version
          
          $yarnGlobalDir = yarn global bin
          $env:Path += ";$yarnGlobalDir"

          yarn global add $PWD
          devspace --version
          yarn global remove devspace
        working-directory: ./dist/npm
